name: CI Build

on:
  # Build main container:
  repository_dispatch:
    types: [build]
  workflow_dispatch:
  push:
    branches: ['main']
    paths-ignore: ['**/*.md']
  # Build release container:
    tags:
      - 'v*.*'
      - 'v*.*.*'
  # Dry run for PRs:
  pull_request:
    branches: ['main']
    paths-ignore: ['**/*.md']

permissions:
  contents: write
  packages: write
  # This is used to complete the identity challenge
  # with sigstore/fulcio when running outside of PRs.
  id-token: write

jobs:
  frontend:
    permissions:
      contents: write
    uses: llamara-ai/llamara-frontend/.github/workflows/build.yaml@main

  backend:
    needs: frontend
    permissions:
      contents: write
      packages: write
      id-token: write
    uses: llamara-ai/llamara-backend/.github/workflows/build.yaml@main
